export const creators = [
  { name: "Książulo", handle: "@ksiazulo", region: "Polska", focus: "street food i lokale z dużym ruchem", weight: 96, platform: "YouTube / TikTok" },
  { name: "Aga Testuje", handle: "@wyzszy_instytut_smaku", region: "Polska", focus: "restauracje, kawiarnie, miejsca premium", weight: 91, platform: "TikTok / Instagram" },
  { name: "Maciej je", handle: "@maciejje", region: "Polska", focus: "rankingi i przewodniki po miastach", weight: 88, platform: "blog / social" },
  { name: "Kraków Food Kati", handle: "@krakowfood.kati", region: "Kraków / Małopolska", focus: "nowe restauracje w Krakowie", weight: 83, platform: "Instagram" },
  { name: "Big Bula Polish Street Food", handle: "@bigbulapolishstreetfood", region: "Polska", focus: "burgery, kebab, food trucki", weight: 83, platform: "TikTok" },
  { name: "Restaurantica", handle: "@restaurantica", region: "Warszawa", focus: "gastro newsy i przewodniki", weight: 82, platform: "Instagram / blog" },
  { name: "Food By Warsaw", handle: "@foodbywarsaw", region: "Warszawa", focus: "restauracje, kawiarnie i nowe miejsca", weight: 80, platform: "Instagram" },
  { name: "Śląski YE", handle: "@slaskiye", region: "Śląsk", focus: "Katowice i region", weight: 79, platform: "social" },
  { name: "Taste of Warsaw", handle: "@tasteofwarsaw", region: "Warszawa", focus: "jedzenie i restauracje w Warszawie", weight: 78, platform: "Instagram" },
  { name: "Warsaw Food Guide", handle: "@warsawfoodguide", region: "Warszawa", focus: "krótkie rekomendacje lokali", weight: 77, platform: "Instagram" },
  { name: "Gdzie zjeść w Poznaniu i Warszawie", handle: "@gdziezjescwpoznaniu", region: "Poznań / Warszawa", focus: "lokalne odkrycia", weight: 76, platform: "Instagram" },
  { name: "Z Widelcem po Wrocławiu", handle: "@zwidelcempowroclawiu", region: "Wrocław", focus: "nowe miejsca we Wrocławiu", weight: 76, platform: "Instagram / blog" },
  { name: "Why Not Gdańsk", handle: "@whynotgdansk", region: "Trójmiasto", focus: "Gdańsk, Sopot, restauracje", weight: 76, platform: "Instagram" },
  { name: "Food4Warsaw", handle: "@food4warsaw", region: "Warszawa", focus: "knajpki i kawiarnie", weight: 75, platform: "Instagram" },
  { name: "Ludzie Huby", handle: "@ludziehuby", region: "Kraków", focus: "krakowski food", weight: 75, platform: "Instagram" },
  { name: "YOZO Mniam Mniam", handle: "@yozo.life", region: "Polska", focus: "bary, budki, szybkie jedzenie", weight: 74, platform: "TikTok / Instagram" },
  { name: "TasteAway", handle: "@blogtasteaway", region: "Polska", focus: "podróże kulinarne i restauracje", weight: 73, platform: "Instagram / blog" },
  { name: "Jedzenie Warszawa", handle: "@jedzeniewarszawa", region: "Warszawa", focus: "przewodnik po lokalach", weight: 72, platform: "Instagram / www" },
  { name: "Foodie Trójmiasto", handle: "@foodietrojmiasto", region: "Trójmiasto", focus: "gdzie zjeść w Trójmieście", weight: 72, platform: "Instagram" },
  { name: "Jemy w Łodzi", handle: "@jemywlodzi", region: "Łódź", focus: "łódzkie otwarcia i recenzje", weight: 72, platform: "www / social" },
  { name: "Gdzie Zjeść Kraków", handle: "@gdziezjesckrakow", region: "Kraków", focus: "rankingi i lokalne aktualizacje", weight: 70, platform: "www / social" },
  { name: "KUKBUK", handle: "@kukbuk", region: "Polska", focus: "trendy gastro i przewodniki", weight: 70, platform: "magazyn / social" },
  { name: "Wife With Knife", handle: "@wifewithknife_com", region: "Łódź", focus: "recenzje restauracji i smaki", weight: 68, platform: "Instagram / blog" },
];

export const openKeywords = [
  "nowy lokal",
  "nowylokal",
  "nowe miejsce",
  "nowemiejsce",
  "nowa restauracja",
  "nowa knajpa",
  "nowa miejscówka",
  "nowa miejscowka",
  "nowe bistro",
  "nowa kawiarnia",
  "otworzył",
  "otworzyła",
  "otworzyli",
  "otwieramy",
  "otwiera się",
  "otwarcie",
  "soft opening",
  "premiera lokalu",
  "startuje",
  "pierwszy tydzień",
  "właśnie ruszył",
  "właśnie ruszyła",
  "od dziś",
  "od dzisiaj",
];

export const rejectKeywords = ["starej", "kultowy", "ranking", "top 10", "po zmianie menu", "kolejny raz"];
