export const creators = [
  { name: "Książulo", handle: "@ksiazulo", region: "Polska", focus: "street food i lokale z dużym ruchem", weight: 96, platform: "YouTube / TikTok" },
  { name: "Aga Testuje", handle: "@wyzszy_instytut_smaku", region: "Polska", focus: "restauracje, kawiarnie, miejsca premium", weight: 91, platform: "TikTok / Instagram" },
  { name: "Maciej je", handle: "@maciejje", region: "Polska", focus: "rankingi i przewodniki po miastach", weight: 88, platform: "blog / social", profileUrl: "https://maciej.je/" },
  { name: "Kraków Food Kati", handle: "@krakowfood.kati", region: "Kraków / Małopolska", focus: "nowe restauracje w Krakowie", weight: 83, platform: "Instagram" },
  { name: "Big Bula Polish Street Food", handle: "@bigbulapolishstreetfood", region: "Polska", focus: "burgery, kebab, food trucki", weight: 83, platform: "TikTok" },
  { name: "Warsaw Foodie", handle: "@warsawfoodie", region: "Warszawa", focus: "nowe otwarcia i przewodnik po restauracjach", weight: 84, platform: "Instagram / Facebook / www", profileUrl: "https://warsawfoodie.pl/" },
  { name: "Restaurantica", handle: "@restaurantica", region: "Warszawa", focus: "gastro newsy i przewodniki", weight: 82, platform: "Instagram / Facebook / blog", profileUrl: "https://www.instagram.com/restaurantica/" },
  { name: "Food By Warsaw", handle: "@foodbywarsaw", region: "Warszawa", focus: "restauracje, kawiarnie i nowe miejsca", weight: 80, platform: "Instagram" },
  { name: "Gdzie Zjeść Warszawa", handle: "@gdziezjescwarszawa", region: "Warszawa", focus: "nowe lokale i opinie o warszawskich miejscach", weight: 80, platform: "Instagram / www", profileUrl: "https://gdziezjescwarszawa.com/" },
  { name: "Śląski YE", handle: "@slaskiye", region: "Śląsk", focus: "Katowice i region", weight: 79, platform: "social", profileUrl: "https://www.instagram.com/slaskiye/" },
  { name: "Nowe we Wro", handle: "@nowewewro", region: "Wrocław", focus: "gastro newsy i nowe miejsca we Wrocławiu", weight: 79, platform: "Instagram", profileUrl: "https://www.instagram.com/nowewewro/" },
  { name: "Wrocławskie Podróże Kulinarne", handle: "@wroclawskiepodrozekulinarne", region: "Wrocław", focus: "największe kulinarne medium o Wrocławiu", weight: 79, platform: "Instagram / Facebook", profileUrl: "https://www.instagram.com/wroclawskiepodrozekulinarne/" },
  { name: "Taste of Warsaw", handle: "@tasteofwarsaw", region: "Warszawa", focus: "jedzenie i restauracje w Warszawie", weight: 78, platform: "Instagram" },
  { name: "Warsaw Food Guide", handle: "@warsawfoodguide", region: "Warszawa", focus: "krótkie rekomendacje lokali", weight: 77, platform: "Instagram" },
  { name: "Wrocławski Smakosz", handle: "@wroclawski_smakosz", region: "Wrocław", focus: "gdzie zjeść we Wrocławiu i nowe polecenia", weight: 77, platform: "Instagram / www", profileUrl: "https://www.instagram.com/wroclawski_smakosz/" },
  { name: "Gdzie zjeść w Poznaniu i Warszawie", handle: "@gdziezjescwpoznaniu", region: "Poznań / Warszawa", focus: "lokalne odkrycia", weight: 76, platform: "Instagram" },
  { name: "Z Widelcem po Wrocławiu", handle: "@zwidelcempowroclawiu", region: "Wrocław", focus: "nowe miejsca we Wrocławiu", weight: 76, platform: "Instagram / blog" },
  { name: "Why Not Gdańsk", handle: "@whynotgdansk", region: "Trójmiasto", focus: "Gdańsk, Sopot, restauracje", weight: 76, platform: "Instagram" },
  { name: "Food4Warsaw", handle: "@food4warsaw", region: "Warszawa", focus: "knajpki i kawiarnie", weight: 75, platform: "Instagram" },
  { name: "Kulinarnie Niepoważni", handle: "@kulinarnieniepowazni", region: "Warszawa", focus: "warszawskie restauracje i przewodniki", weight: 75, platform: "Instagram / Facebook / blog", profileUrl: "https://kulinarnieniepowazni.pl/" },
  { name: "Ludzie Huby", handle: "@ludziehuby", region: "Kraków", focus: "krakowski food", weight: 75, platform: "Instagram" },
  { name: "MYTUJEMY", handle: "@mytujemy", region: "Poznań", focus: "jedzeniowy przewodnik po Poznaniu", weight: 75, platform: "Instagram / www", profileUrl: "https://www.instagram.com/mytujemy/" },
  { name: "YOZO Mniam Mniam", handle: "@yozo.life", region: "Polska", focus: "bary, budki, szybkie jedzenie", weight: 74, platform: "TikTok / Instagram" },
  { name: "Krakow Foodie", handle: "@krakowfoodie", region: "Kraków", focus: "krakowskie gastro newsy i rekomendacje", weight: 74, platform: "Instagram / Facebook / www", profileUrl: "https://www.instagram.com/krakowfoodie/" },
  { name: "Poznań Na Widelcu", handle: "@poznannawidelcu", region: "Poznań", focus: "nowe restauracje i lokale w Poznaniu", weight: 74, platform: "Instagram / Facebook / www", profileUrl: "https://www.poznannawidelcu.pl/" },
  { name: "TasteAway", handle: "@blogtasteaway", region: "Polska", focus: "podróże kulinarne i restauracje", weight: 73, platform: "Instagram / blog" },
  { name: "Jedzenie Warszawa", handle: "@jedzeniewarszawa", region: "Warszawa", focus: "przewodnik po lokalach", weight: 72, platform: "Instagram / www" },
  { name: "Foodie Trójmiasto", handle: "@foodietrojmiasto", region: "Trójmiasto", focus: "gdzie zjeść w Trójmieście", weight: 72, platform: "Instagram" },
  { name: "Jemy w Łodzi", handle: "@jemywlodzi", region: "Łódź", focus: "łódzkie otwarcia i recenzje", weight: 72, platform: "www / social", profileUrl: "https://jemywlodzi.pl/" },
  { name: "Have a Bite Kraków", handle: "@haveabitekrakow", region: "Kraków", focus: "krakowskie restauracje, kawiarnie i przewodniki", weight: 72, platform: "Instagram / Facebook / www", profileUrl: "https://www.haveabite.co/" },
  { name: "Foodhunterki", handle: "@foodhunterki", region: "Poznań", focus: "kulinarne polecenia z Poznania i okolic", weight: 71, platform: "Instagram", profileUrl: "https://www.instagram.com/foodhunterki/" },
  { name: "Ślinka Cieknie", handle: "@slinkacieknie", region: "Poznań / Polska", focus: "lokale polecane przez food creatorów", weight: 71, platform: "Instagram / www", profileUrl: "https://www.slinkacieknie.pl/" },
  { name: "Gdzie Zjeść Kraków", handle: "@gdziezjesckrakow", region: "Kraków", focus: "rankingi i lokalne aktualizacje", weight: 70, platform: "www / social", profileUrl: "https://gdziezjesckrakow.com/" },
  { name: "KUKBUK", handle: "@kukbuk", region: "Polska", focus: "trendy gastro i przewodniki", weight: 70, platform: "magazyn / social", profileUrl: "https://www.kukbuk.pl/" },
  { name: "Pitu Pitu Katowice", handle: "@pitupitukatowice", region: "Katowice / Śląsk", focus: "baza nowych i popularnych miejsc w Katowicach", weight: 70, platform: "www / social", profileUrl: "https://www.pitupitu.pl/katowice/" },
  { name: "Śląskie Smaki", handle: "@slaskiesmaki", region: "Katowice / Śląsk", focus: "śląski szlak kulinarny i lokalne gastro aktualizacje", weight: 70, platform: "Instagram / Facebook / www", profileUrl: "https://www.instagram.com/slaskiesmaki/" },
  { name: "In Szczecin", handle: "@inszczecin", region: "Szczecin", focus: "jedzenie, miejsca i nowe punkty w Szczecinie", weight: 70, platform: "Instagram", profileUrl: "https://www.instagram.com/inszczecin/" },
  { name: "Dusiowa Kuchnia", handle: "@dusiowakuchnia", region: "Trójmiasto", focus: "lokalne jedzenie i restauracyjne polecenia", weight: 69, platform: "Instagram / Facebook / blog", profileUrl: "https://www.instagram.com/dusiowakuchnia/" },
  { name: "Wife With Knife", handle: "@wifewithknife_com", region: "Łódź", focus: "recenzje restauracji i smaki", weight: 68, platform: "Instagram / blog" },
  { name: "Foodies we Wro", handle: "@foodieswewro", region: "Wrocław", focus: "społeczność FB z lokalnymi odkryciami i nowymi miejscami", weight: 67, platform: "Facebook group", profileUrl: "https://www.facebook.com/groups/foodieswewro" },
];

export const curatedSignals = [
  {
    id: "curated-stacja-baluty",
    venue: "Stacja Bałuty",
    city: "Łódź",
    district: "Bałuty",
    address: "Sierakowskiego 88",
    category: "Pizza i burgery",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowy lokal Stacji Retkinia na Bałutach. Źródło opisuje drugi lokal z pizzą i burgerami pod adresem Sierakowskiego 88.",
    sourceUrl: "https://jemywlodzi.pl/stacja-retkinia-ma-nowa-stacje-na-balutach/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-brunchery-warsaw",
    venue: "The Brunchery Bread & Bar",
    city: "Warszawa",
    district: "Wola",
    address: "Wronia 10",
    category: "Brunch / restauracja",
    creator: "Warsaw Foodie",
    handle: "@warsawfoodie",
    caption:
      "Nowe miejsce na brunch, lunch i aperitivo na Woli. Warsaw Foodie opisuje otwarcie restauracji The Brunchery Bread & Bar przy Wroniej 10.",
    sourceUrl: "https://warsawfoodie.pl/2026/02/the-brunchery-bread-bar-nowe-miejsce-na-brunch-lunch-i-aperitivo-na-woli/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-moa-pacific-food",
    venue: "Moa Pacific Food",
    city: "Warszawa",
    district: "Śródmieście",
    address: "Nowolipki 15",
    category: "Hawajskie / bowl",
    creator: "Warsaw Foodie",
    handle: "@warsawfoodie",
    caption:
      "Nowa restauracja z kuchnią hawajską przy Nowolipki 15, opisana przez Warsaw Foodie jako świeże otwarcie w Warszawie.",
    sourceUrl: "https://warsawfoodie.pl/2026/01/moa-pacific-food-nowa-restauracja-z-kuchnia-hawajska/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-yoi-ramen",
    venue: "YOI Ramen",
    city: "Warszawa",
    district: "Śródmieście",
    address: "Dobra 40",
    category: "Ramen",
    creator: "Warsaw Foodie",
    handle: "@warsawfoodie",
    caption:
      "Nowa ramenownia w Elektrowni Powiśle. Źródło wskazuje nowe miejsce YOI Ramen przy Dobrej 40.",
    sourceUrl: "https://warsawfoodie.pl/2026/02/yoi-ramen-nowa-ramenownia-w-elektrowni-powisle/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-vini-goclaw",
    venue: "VINI",
    city: "Warszawa",
    district: "Praga Południe",
    address: "Skalskiego 3",
    category: "Włoskie",
    creator: "Warsaw Foodie",
    handle: "@warsawfoodie",
    caption:
      "Nowa włoska restauracja na Gocławiu. Warsaw Foodie opisuje otwarcie VINI przy Skalskiego 3.",
    sourceUrl: "https://warsawfoodie.pl/2026/02/vini-nowa-wloska-restauracja-na-goclawiu/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-nie-pytaj-20",
    venue: "Nie pytaj 2.0",
    city: "Łódź",
    district: "Nowa Sukcesja",
    address: "Rembielińskiego 4",
    category: "Kawiarnia",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowa odsłona kawiarni Nie pytaj 2.0 w większej przestrzeni przy Rembielińskiego 4.",
    sourceUrl: "https://jemywlodzi.pl/szlakiem-slodkosci-nowe-kawiarnie-w-lodzi/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-maru-lodz",
    venue: "Maru",
    city: "Łódź",
    district: "Śródmieście",
    address: "Piotrkowska 64",
    category: "Matcha / kawiarnia",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowe miejsce Maru przy Piotrkowskiej 64, rozwinięte z food trucka na OFF Piotrkowska.",
    sourceUrl: "https://jemywlodzi.pl/szlakiem-slodkosci-nowe-kawiarnie-w-lodzi/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-sisi-cakes",
    venue: "SISI Cakes",
    city: "Łódź",
    district: "Bałuty",
    address: "Łagiewnicka 80/98",
    category: "Cukiernia / kawiarnia",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowe kameralne miejsce SISI Cakes z monoporcjami, sernikami baskijskimi i tartami.",
    sourceUrl: "https://jemywlodzi.pl/szlakiem-slodkosci-nowe-kawiarnie-w-lodzi/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-pafu",
    venue: "Pafu",
    city: "Łódź",
    district: "Polesie",
    address: "Wólczańska 223",
    category: "Pracownia wypieków",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowe miejsce Pafu przy Wólczańskiej 223, pracownia wypieków z francuskim rzemiosłem.",
    sourceUrl: "https://jemywlodzi.pl/szlakiem-slodkosci-nowe-kawiarnie-w-lodzi/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-acanti",
    venue: "Acanti",
    city: "Łódź",
    district: "Centrum",
    address: "Traugutta 12",
    category: "Restauracja",
    creator: "Jemy w Łodzi",
    handle: "@jemywlodzi",
    caption:
      "Nowe kulinarne otwarcie Acanti w odrestaurowanej kamienicy T12 przy Traugutta 12.",
    sourceUrl: "https://jemywlodzi.pl/acanti-mocne-kulinarne-otwarcie-w-lodzi/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-haust",
    venue: "Haust",
    city: "Kraków",
    district: "Kazimierz",
    address: "Berka Joselewicza 18",
    category: "Restauracja",
    creator: "Kraków Food Kati",
    handle: "@krakowfood.kati",
    caption:
      "Nowe miejsce wyróżnione w zestawieniu Kraków Food w kategorii najlepszych nowych miejsc 2025.",
    sourceUrl: "https://krakowfood.pl/najlepsze-restauracje-w-krakowie-2025-plebiscyt/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-osma-rano",
    venue: "Ósma Rano",
    city: "Kraków",
    district: "Stare Miasto",
    address: "Podwale 4",
    category: "Śniadania / brunch",
    creator: "Kraków Food Kati",
    handle: "@krakowfood.kati",
    caption:
      "Nowe miejsce Ósma Rano przy Podwale 4, wskazane w plebiscycie Kraków Food jako jedno z najlepszych nowych miejsc.",
    sourceUrl: "https://krakowfood.pl/najlepsze-restauracje-w-krakowie-2025-plebiscyt/",
    detectedAt: "2026-05-14",
    verified: false,
  },
  {
    id: "curated-udon-san",
    venue: "Udon-San",
    city: "Kraków",
    district: "Krowodrza",
    address: "Królewska 57",
    category: "Japońskie / udon",
    creator: "Kraków Food Kati",
    handle: "@krakowfood.kati",
    caption:
      "Nowe otwarcie Udon-San dostrzeżone w zestawieniu Kraków Food; lokal działa przy Królewskiej 57.",
    sourceUrl: "https://krakowfood.pl/najlepsze-restauracje-w-krakowie-2025-plebiscyt/",
    detectedAt: "2026-05-14",
    verified: false,
  },
];

export const openKeywords = [
  "nowy lokal",
  "nowylokal",
  "nowe miejsce",
  "nowemiejsce",
  "nowa restauracja",
  "nowa knajpa",
  "nowa miejscówka",
  "nowa miejscowka",
  "nowe bistro",
  "nowa kawiarnia",
  "otworzył",
  "otworzył się",
  "otworzyła",
  "otworzyło się",
  "otworzyli",
  "otwieramy",
  "otwiera się",
  "otwarcie",
  "nowo otwarte",
  "soft opening",
  "premiera lokalu",
  "startuje",
  "rusza",
  "pierwszy tydzień",
  "świeże gastro",
  "swieze gastro",
  "właśnie ruszył",
  "właśnie ruszyła",
  "wlasnie ruszyl",
  "wlasnie ruszyla",
  "drugi lokal",
  "od dziś",
  "od dzisiaj",
];

export const rejectKeywords = [
  "starej",
  "kultowy",
  "ranking",
  "top 10",
  "topka",
  "najlepsze restauracje",
  "ulubione miejsca",
  "po zmianie menu",
  "nowe menu",
  "kolejny raz",
  "wracam do",
  "odwiedzam ponownie",
];
